---
- name: Create Postgres data volume
  containers.podman.podman_volume:
    name: gitea-postgres-data
    state: present
    label:
      app: gitea

- name: Create Postgres Container
  containers.podman.podman_container:
    name: gitea-postgres
    image: 'postgres:{{ gitea_postgres_version }}'
    pod: gitea
    conmon_pidfile: /var/lib/containers/pids/gitea-postgres.pid
    env:
      POSTGRES_USER: gitea
      POSTGRES_PASSWORD: gitea
      POSTGRES_DB: gitea
    volume:
      - gitea-postgres-data:/var/lib/postgresql/data
    state: started

- name: Generate systemd unit content
  shell: set -o pipefail && podman generate systemd gitea-postgres -n --restart-policy on-failure | tail -n +5
  changed_when: False
  register: systemd

- name: Create unit file
  copy:
    content: '{{ systemd.stdout }}'
    dest: /etc/systemd/system/container-gitea-postgres.service
    owner: root
    group: root
    mode: '0644'
  register: unit_file
  notify:
    - daemon-reload
    - Restart gitea-postgres

- name: Start Gitea Postgres container
  systemd:
    name: container-gitea-postgres.service
    state: started
    enabled: yes
  when: not unit_file.changed
