---
- name: daemon-reload
  systemd:
    daemon-reload: yes

- name: Restart gitea-postgres
  systemd:
    name: container-gitea-postgres.service
    state: restarted

- name: Restart gitea-proxy
  systemd:
    name: container-gitea-proxy.service
    state: restarted

